imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: doctrine.yml }
    - { resource: fos_user.yml }
    - { resource: hwi_oauth.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ro

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets:
        base_urls:
            - '%cdn.hostname%'
        version_strategy: 'AppBundle\Asset\VersionStrategy\JsonManifestVersionStrategy'
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        site_name: '%param.site_name%'
        site_social:
            - { name: facebook, url: '%site.social.facebook%' }
            - { name: twitter, url: '%site.social.twitter%' }
            - { name: youtube, url: '%site.social.youtube%' }
            - { name: 'google-plus', url: '%site.social.google_plus%' }
        site_contact:
            - { type: address, value: '%site.contact.email%' }
            - { type: tel, value: '%site.contact.telephone%' }
    form_themes:
        - bootstrap_3_layout.html.twig

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
