# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    role_hierarchy:
      ROLE_REDACTOR:      [ROLE_USER]
      ROLE_ADMIN:         [ROLE_REDACTOR]
      ROLE_SYSOP:         [ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]
      ROLE_SUPER_ADMIN:   [ROLE_SYSOP]

    access_control:
      - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/panou/cont/*, roles: ROLE_USER }
      - { path: ^/panou/redactor/*, roles: ROLE_REDACTOR }
      - { path: ^/panou/admin/*, roles: ROLE_ADMIN }
      - { path: ^/(_(profiler|wdt))/*, roles: ROLE_SYSOP }

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            logout: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            oauth:
                resource_owners:
                    facebook: "/panou/cont/conectare/verificare/facebook"
                login_path: /panou/cont/autentificare
                failure_path: /panou/cont/autentificare
                use_forward: false
                oauth_user_provider:
                    service: my_user_provider