<?php

class bla {

const COUNT_HEADER_LEFT_1 = 0;
const COUNT_HEADER_RIGHT_1 = 0;
const COUNT_MENU_BOTTOM_1 = 0;
const COUNT_ARTICLE_RIGHT_1 = 0;
const COUNT_HOMEPAGE_FEATURED_BOTTOM_1 = 0;
const COUNT_HOMEPAGE_VIDEO_TOP_1 = 0;
const COUNT_HOMEPAGE_VIDEO_BOTTOM_1 = 0;
}